{% set name = "aws-cdk.cloud-assembly-schema" %}
{% set version = "2.145.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.cloud-assembly-schema-{{ version }}.tar.gz
  sha256: d1fc5e830fcf4a8e817f68132bfe8e843ee815fc4a54af565ba2ddecc57885ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >=3.8
    - python-jsii >=1.98.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.cloud_assembly_schema
    - aws_cdk.cloud_assembly_schema._jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: Cloud Assembly Schema
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0 AND BSD-4-Clause
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
